### ISSUE TITLE
UI: Send

### ISSUE THREAD

**Issue by dexX7** [zathras-crypto/omnicore#17]
![3_send](https://cloud.githubusercontent.com/assets/5836089/6162666/2dfa93d8-b287-11e4-9e33-d99881990e55.png)
- [x] 6) ~~When selecting an address to spent from, it's incredibly difficult to choose one, because it's a plain list of addresses, basically random characters, without further information. Say there are five available, what could one do? Switch back to the balance tab, then try to remember the balance + address?~~ edit: marked as done, as the issue is actually more about getting a "send from" in "balances"
- [x] 7) I'm not a fan of the BTC threshold warning, which is pretty arbitrary, and suggest to show the BTC balance all the time, without further notice or warning.
- [x] 8) ~~The amount field could be enhanced by "increase and decrease of a unit within the number field".~~ edit: requires extension of [QDoubleSpinBox](http://qt-project.org/doc/qt-4.8/qdoublespinbox.html), probably not worth at this point

**Comment by zathras-crypto** [comment]
Could you clarify 6 for me mate?  Why would you need to switch back to balances tab when balance info is on the right of the combo?  Perhaps this is just the way I'm used to using it (click into the combo, then tap down arrow key repeatedly until I find an address that has enough balance) - I don't ever need to switch back to balances tab.

**Comment by zathras-crypto** [comment]
But yeah balances can be added to the combo if that's desired (this is how I did it with Chest wallet).

Thanks
Z

**Comment by dexX7** [comment]
> Why would you need to switch back to balances tab when balance info is on the right of the combo?

Haha yeah, well, this was probably a bit extreme. Navigating up and down and looking at the balance label would work as well. My point is basically: the more addresses there are, the more difficult it gets. It works for a few well, but it's a bit painful to search for a specific address in general.

I think the most straight forward solution would be to have a "send from this address" option in the balance tab.

**Comment by zathras-crypto** [comment]
Sure sure, understood.  Let me look into it :)

**Comment by dexX7** [comment]
Of all others, "copy address" and "send from this address" would really be the biggst improvement in my opinion, awesome! .. :)

**Comment by zathras-crypto** [comment]
Re 7) it's not the BTC balance we're showing actually bud - it's the amount we were able to select for use as inputs (feeCheck is essentially using input selection).  I agree this is counter to an easy UX though, so since this page is solely talking about simple sends, we can hard code for now.  

What I'll go with (unless opposition) is a hard coded 2000 satoshi check.  If you have over 2000 satoshi we'll let you send the tx, if not we won't (and will label simply that there are not enough BTC for fees at the sending address without getting into specifics).

Note this is purely a UX thing, there will be no changes to sending via RPC.

Thoughts?

**Comment by dexX7** [comment]
> It's not the BTC balance we're showing actually bud - it's the amount we were able to select for use as inputs ... What I'll go with (unless opposition) is a hard coded 2000 satoshi check. If you have over 2000 satoshi we'll let you send the tx, if not we won't.

Ah, I see. +1 for "either send or no send"

**Comment by zathras-crypto** [comment]
Updated send page - https://github.com/zathras-crypto/mastercore/commit/e2c56fbac3c9ac3766965c08314d7ac64a7e2237

**Comment by dexX7** [comment]
As posted in the PR: I really like the warning now. I'm not sure about the mix of amounts and addresses though. If it is to expect that a user has not many addresses for a currency, then I think keeping the balances out of the list might look cleaner. I'm really not sure...

Quick note regarding the fees and the calculation: the current coin selection is somewhat odd imho and using magic numbers for size calculation will likely run into problems at some point. Is that correct? If so, I should probably dig out a refactored version which uses the internal wallet coin selection and approximates the transaction size (was a byproduct of implementing Bitcoin STO). Depending on the need of course, as it would probably still need some refinement to fit into the current model.

**Comment by zathras-crypto** [comment]
Hehe, hmm let me have a think about addresses / balances - I can put them
back to original that's certainly an option, but one of the reasons I did
it was because I remember getting similar requests (to display balance in
address selection) for MasterChest wallet back in the day.  Will think
about it a bit more :)

Re input selection - we'd need to tread very carefully there - current
methodology does have a magic number as you say (20*0.0001) but we should
be clear that's not a requirement, only a maximum.  Just means we will stop
selecting inputs if we have selected >0.002 BTC already as this is deemed
to be sufficient for any transaction size - doesn't however mean you need
that much - it's just a 'stop' if you will (to avoid selecting more inputs
than needed).  Even if we hit the end of iterating our available UTXOs for
the address without reaching the max we still attempt to send the
transaction as 99 times out of 100 we need far less BTC than the maximum.

If input selection were to be redone I'd like it to be done intelligently
(heuristically?) utilizing the metrics of the underlying (Bitcoin) network
- things like size and age of the inputs that affect the priority of a
  given transaction.  I'd also like it to be done with a secondary sort on
  smallest to largest inputs to ensure old reference outputs are collected up
  and spent instead of left hanging around.  But on this one I think we have
  something that works already, so unless a practical need emerges to be
  smarter with our input selection near term, I think this is something that
  will be for a bit later.

Side note, the UI takes it's own guess at this with a 0.00022 minimum (it
won't let you send with less than that, even though technically you may be
able to via RPC - but we needed a cutoff somewhere and a plain simple send
being <2K is a reasonably safe assumption for the vast majority of
transactions - if not you'll simply get a fees error when Core attempts to
commit the transaction).

Thanks
Z

**Comment by dexX7** [comment]
It looks like the Core input selection, very roughly said, tries to select coins as random as possible, and loops to find a subset of unspent outputs that satisfies the target value + fees. It's hardly possible in one, because the number of selected inputs and priority has an impact on the fee. You're very right regarding this being an actually bigger topic.

You're also right about focusing on what's more important, because we can easily get away with some magic threshold for now, as it should not concern or even be visible to most users.

A very simple adjustment I propose though would be to replace [qt/sendmpdialog.cpp#L153](https://github.com/zathras-crypto/mastercore/blob/e2c56fbac3c9ac3766965c08314d7ac64a7e2237/src/qt/sendmpdialog.cpp#L153):

``` c++
if (inputTotal<22000)
```

... to use something like `someFactorN * theActualFee` instead of `22000`, which would equally work (or not work) for any setting a user may use, and show the warning, if it's below that value.

**Comment by zathras-crypto** [comment]
Took a bit to get this right, but I think I now have got something that's perhaps the best of both worlds - let me know your thoughts :) https://github.com/zathras-crypto/mastercore/commit/0b22cfe4b935f64ee09269774d287da98dde0b75

**Comment by dexX7** [comment]
Ah, but one more note to [qt/sendmpdialog.cpp#L273-L280](https://github.com/zathras-crypto/mastercore/blob/e2c56fbac3c9ac3766965c08314d7ac64a7e2237/src/qt/sendmpdialog.cpp#L273-L280):

``` c++
// check if there are enough BTC for fees
int64_t inputTotal = feeCheck(strFromAddress);
if (inputTotal<22000)
{
    QMessageBox::critical( this, "Unable to send transaction",
    "The sending address does not have enough Bitcoin to cover transaction fees.\n\nPlease forward a small amount of BTC to the sending address in order to send Omni transactions from this address." );
    return;
}
```

Is there a reason to keep this check, instead of simply trying to send and catch the -206 "insufficient funds" error (IIRC), as you already do?

Edit: will start building in a minute and update.. :)

**Comment by zathras-crypto** [comment]
That's a new check - it's part of the "you can either send or you can't" mentality to UX.  If you have under 0.00022 we won't let you send from the UI full stop.

I figured it would be poor to show a warning saying "you will not be able to send this transaction" but clicking send still successfully sends it.

Long story short, Core will attempt to create any transaction you throw at it, even if there was only 1 satoshi for fees.  It'd fail with that error code as you note.    Basically there is (currently) only one way to know if a transaction will be successfully committed and that's to create the transaction and try and commit it.  Prior to that it's all guess work re fees until we rewrite input selection to be smarter.

That's why the inital warnings were written as "you probably don't have enough for fees, but we can't be sure so you can try and send anyway" which I think was your 'WTF' feedback lol.  So for now in order to give that definitive "yay/nay" we need a number to evaluate against without creating and attempting to commit a transaction.  That's where the 22000 comes from (20000 for up to 2KB of tx size, 2000 for exo, ref & multisig outputs) a number intended to catch 99+ out of 100 sends without error.  

Hope that makes sense :)

**Comment by dexX7** [comment]
Sure, it does, and I sort of support this approach. My earlier point was more about: don't use the assumption of a 2 KB transaction (which is fine) in combination with a fixed value. IIRC (will update on this in a minute as well), there is a global `nTransactionFee` which could be used as multiplicator instead.

I didn't intend to start such a huge discussion, but while thinking about it, and I'm probably not qualified to answer it: does it increase the user experience at all, when warning or preventing an action, if instant feedback regarding success or failure follows anyway?

**Comment by zathras-crypto** [comment]
I'm open to using a nTransactionFee multiplier sure :)

I'm also open to reverting to the existing "always try to send" mentality too when reflecting on the instant feedback.  We'd remove the fixed fee check and use a rewording for the warning of:
`WARNING: You will not be able to send this transaction.  The sending address does not have enough BTC to cover transaction fees.` 
to
`WARNING: The sending address is low on BTC for transaction fees.  You may need to forward a small amount of BTC to the sending address in order to send this transaction.`
User could then click send and it'd be up to Core as to whether it can commit the transaction (same model as RPC).  Not sure which is the best UX here.

**Comment by dexX7** [comment]
Hehe yeah, me neither.

Confirmed: `nTransactionFee` it is. (edit: it's the fee paid for 1000 byte in satoshi as int64_t)

**Comment by dexX7** [comment]
Before:

![old_send](https://cloud.githubusercontent.com/assets/5836089/6180368/2a628be8-b324-11e4-9724-288aed07508e.png)
![old_send_dropdown](https://cloud.githubusercontent.com/assets/5836089/6180369/2e1f9cb2-b324-11e4-8760-aef945f8ec64.png)

## 

Now:

![new_send](https://cloud.githubusercontent.com/assets/5836089/6180373/31a62ebe-b324-11e4-8498-b2cb52897b07.png)
![new_send_dropdown](https://cloud.githubusercontent.com/assets/5836089/6180374/34035768-b324-11e4-9bc1-acbd7e0275ca.png)

## 

Well done, in my opinion! :)

Maybe remove `(Available:` ____ `)`, and show the balance with all digits and currency.

**Comment by dexX7** [comment]
Just saw the address is now also copyable, very nice.

**Comment by dexX7** [comment]
This is what I had in mind:

![send_dropdown_proposal](https://cloud.githubusercontent.com/assets/5836089/6180670/b2ca73c0-b328-11e4-8175-f935d178ee8c.png)

**Comment by zathras-crypto** [comment]
> This is what I had in mind:

https://github.com/zathras-crypto/mastercore/commit/ee3e5fea9efb55b4251607296640261fa46f7d5c

**Comment by zathras-crypto** [comment]
Have to go one way or the other so made a call (for 0.0.9.1 at least) on send fees UX https://github.com/zathras-crypto/mastercore/commit/dc1645699972b9c48bd3b64d9dc31b45c12bb3cc

**Comment by dexX7** [comment]
I'm really impressed by the work you've done the last days, while I spent most of the time testing stuff and on theory-crafting. Yesterday was used to simulate fee scenarios, but I basically wasted my time on edge cases. The essence is this: my initial fear was that our current transaction generation could result in a situation where the coin selection is unsolvable, even with very high threshold values, for example because dust is not redeemed for a long time, and then, in one transaction, there is nothing else left than dust and a gigantic transaction is created.

Turned out this was never the case, but quite the contrary actually. The primary behavior is that unspent outputs are combined over time, e.g. starting when with 1000x 0.00000546 BTC outputs, it usually (always?) ends up with just two, after many, many sends, with one being dust from the reference output and the other one being change, which grew over time due to it's sweeping behavior.

What should be factored in however is the minRelayTxFee, which is responsible for the minimum dust values.

If my calculation isn't incorrect, than the maximum size of a Simple Send transaction, created by Master Core via it's UI should never ever be larger than 1080 byte, based on:
- 5x pay-from-pubkey-hash input with uncompressed public keys (5x 0.00000546 BTC)
- 1x pay-to-pubkey-hash output for exodus (1x 0.00000546 BTC)
- 1x pay-to-pubkey-hash output for reference (1x 0.00000546 BTC)
- 1x pay-to-pubkey-hash output for change (1x 0.00000546 BTC)
- 1x bare-multisig data packet with uncompressed public key (1x 0.00000780 BTC)

To pay for the outputs, we'd need, when rounding up, 3 \* minRelayTxFee. _Edit: just to clarify, I stated BTC values, but the minRelayTxFee relates to transaction size and results in BTC values._

So, with some rounding up, this results in the formula:

``` c++
int64_t minRequiredAmount = 3 * CTransaction::nMinRelayTxFee + 2 * nTransactionFee;
```

This value is also sufficient, if the minRelayTxFee is cut further by a factor of 100, resulting in the theoretical minimum of 0.00000006 BTC to 0.00000008 BTC per output, which in sum equal 0.00000026 BTC. To fund this, with the minimum values possible in this context, we also get away with 5 inputs a 0.00000006 BTC.

To be clear: this might sound as an overoptimized approach which might break, if I'm slightly off, but in terms of transaction fees we pay for `2 KB`, while we should never ever create a transaction with a size of more than `1.08 KB` and in terms of relay fees: we're safe with `3 * relay fee`, because in the worst case, we'd actually only require `2.6 * relay fee`, in the common case `2.418 * relay fee` and in the best case `1.776 * relay fee`.

**Note:** this value can very safely be used for the UI warning, but this is based on the assumption that Simple Sends are created and crowdsales with long descriptions, extra outputs or whatever else might be over the limit.

As future outlook: sooner or later the internal coin selection and transaction generation gets replaced and we simply have a `GetMinFeeFor(theTransaction)` method or so, at least that's what I hope.. :)

I'm currently pulling and rebuilding based on the lastest changes, and then I'm going to push a PR with those numbers, after a final confirmation of running all tests.

**Comment by zathras-crypto** [comment]
Merged https://github.com/zathras-crypto/mastercore/pull/22

**Comment by dexX7** [comment]
Done.

**Comment by zathras-crypto** [comment]
FYI @dexX7 doesn't look like `nMinRelayTxFee` is part of CTransaction class in 0.10, and looks like `nTransactionFee` is gone too.

**Comment by dexX7** [comment]
Hey @zathras-crypto: I'm aware. :)

Slightly related, but maybe this is of use: I pushed a 0.10 based `OP_RETURN` branch, created a few days ago to port your class C work to the new codebase:

https://github.com/dexX7/bitcoin/commits/ocore-0.10-op-return

**Comment by dexX7** [comment]
Sorry, I sort of missed the actual answer:

`::minRelayTxFee`:
https://github.com/dexX7/bitcoin/blob/omnicore-0.0.9.2-no-history/src/main.cpp#L58

And if I'm not mistaken, then this should be the transaction fee `payTxFee`:
https://github.com/dexX7/bitcoin/blob/omnicore-0.0.9.2-no-history/src/wallet.cpp#L28

All this changed a bit, and probably a good example is the 0.10 based `GetDustLimit()`: https://github.com/dexX7/bitcoin/commit/4d90d84cce4b1b3966ad7f2a743afa20a0942bbc

**Comment by zathras-crypto** [comment]
Heh what a legend :)
