### ISSUE TITLE
UI: report progress of initial parsing

### ISSUE THREAD

**Issue by dexX7** [zathras-crypto/omnicore#35]
I'm currently synchronizing on mainnet and it takes like several minutes already, while the interface appears to be completely frozen.

According the the `mastercore.log` transactions are processed, so this issue is related to UI responsiveness and feedback during the initial (Omni/Master) transaction parsing.

**Comment by zathras-crypto** [comment]
Yeah we'd need to pass back progress back to init.cpp so we can update the splash - I assume you currently just see "Parsing Master Protocol Transactions..." while it parses (which needs renaming anyway)?

**Comment by dexX7** [comment]
There is an UI signal `Progress`, but I wasn't able to integrate it.

> Parsing Master Protocol Transactions...

... is fine, if the splash screen is visible. But this is not granted and when clicking somewhere else, at least for me I'm unable to focus it again and it simply appears as if the program is frozen.

Edit: on mainnet this creates an odd impression, because parsing takes several minutes.

**Comment by zathras-crypto** [comment]
Hmm, I do see your point, however is this not kind of inherited from Bitcoin Core?  For example block verification - this can take a couple minutes on a slow system (default 288 blocks at level 3) where the splash will state "Verifying blocks..." and if you switch away, you have no icon to switch back to the splash, it appears hung and you don't really know what's going on?

I definitely think we can address the text we display on the splash (as in present the progress) since we know a) the height of the main chain and b) the last block we processed Omni transactions for, thus can "percent% complete" it or even bang in a progress bar, potentially hijacking a similar approach to 'rescanning' (when a new wallet file is swapped in, blocks are rescanned from last block recorded in wallet to current height of chain to update any missing txs and this process includes a % progress on the splash).  But as to the splash being a window that can be re-activated once switched away from, I'd have to dive into that a bit further mate.

**Comment by dexX7** [comment]
Okay, I just checked it. Bitcoin Core 0.9 freezes during start as well, while Bitcoin Core 0.10 is _fully_ responsive and can even be shutdown.

So let's postpone this to a Core 0.10 based release.

**Comment by dexX7** [comment]
Since this is not really feasible with 0.9, and solved in 0.10, there is not much to do here imho.

Anything like `GuessVerificationProcess` to indicate the status of the progress can be discussed later.
