### ISSUE TITLE
UI: swap colors in transaction history?

### ISSUE THREAD

**Issue by dexX7** [zathras-crypto/omnicore#47]
Just wondering: right now outgoing transactions are green and incoming transactions are red.

Should probably be the other way around?

![colors](https://cloud.githubusercontent.com/assets/5836089/6417639/0a604cb8-beaf-11e4-85fa-7ccf5281f9b8.png)

**Comment by zathras-crypto** [comment]
Yeah not sure how that happened!

Supposed to be:
- Red - funds outbound
- Green - funds inbound
- Black - funds not moved (each offer to trade or tagging savings address etc) - not 100% on what I think behaviour should be here but since those features are not yet available probably moot for now.

Fixed in https://github.com/zathras-crypto/mastercore/commit/8313f27be823bdb6bd0034fbc91d7f63b408decf

**Comment by dexX7** [comment]
Looks good. Black _could_ be used for send-to-self transactions for example, but let's keep it simple for now.
