### ISSUE TITLE
Audit failure when running Boost tests

### ISSUE THREAD

**Issue by dexX7** [zathras-crypto/omnicore#65]
Re: the spock thread and the audit failure, when running the Boost tests  (with some extra output):

```
$ ./src/test/test_bitcoin --log_level=all
Auditor was notified block 0 has begun processing
Initializing Omni Core v0.0.9.2-dev [unittest]
Loading trades database: OK
Loading send-to-owners database: OK
Loading transactions database: OK
Loading smart property database: OK
Auditor initialized
Exodus balance: 0.00000000 MSC
Omni Core initialization completed
mastercore_handler_block_end: nBlockNow=0, devmsc=18446744073709541697
PropertyTotalChanged: increase=1, propertyId=1, amount=-9919, reason=Dev MSC award (block: 0)
PropertyTotalChanged: cachedValue=0, stateValue=0, newValue=-9919
Auditor has detected inconsistencies when attempting to update the total amount of tokens for property 1
Type:increase  Total cached:0, Amount changed:-9919, Total cached after update:-9919, Total from state:0

Error: Shutting down due to audit failure.  Please check mastercore.log for details
```

A few notes:
- [mastercore.cpp#L820](https://github.com/zathras-crypto/mastercore/blob/76fccc7e32b01b96d518865edcd8f6fc4ef16d77/src/mastercore.cpp#L820): the `devmsc` calculation returns an error code `-9919`, because there are no `devmsc` at the time of block 0
- [mastercore.cpp#L4046](https://github.com/zathras-crypto/mastercore/blob/76fccc7e32b01b96d518865edcd8f6fc4ef16d77/src/mastercore.cpp#L4046): `devmsc` is `uint64_t`, while it should probably be `int64_t`, and this results in the seemingly positive number of `18446744073709541697`

So in fact, the amount actually didn't increase at all, but due to the unsignedness, the check `(devmsc > 0)` is passed nevertheless.

``` diff
@@ -4045,3 +4045,3 @@ int mastercore_handler_block_end(int nBlockNow, CBlockIndex const * pBlockIndex,
 // 2) update the amount in the Exodus address
-  uint64_t devmsc = 0;
+  int64_t devmsc = 0;
   unsigned int how_many_erased = eraseExpiredAccepts(nBlockNow);
```

... fixes it and the tests run fine then.. :)

But it sort of makes me wonder, why there are (not only one) place where `uint64_t` are used for token amounts at all.

**Comment by zathras-crypto** [comment]
Brilliant - perfect explanation - thank you dude :)

> But it sort of makes me wonder, why there are (not only one) place where uint64_t are used for token amounts at all.

Well, originally we weren't actually going to cap token counts at 9 gazillion, they were going to be capped at 18 gazillion (unsigned 64) - it was only once we got into forking Bitcoin Core for our reference we started pressing kind of hard for us to cap at 9 gazillion (signed 64) because `int64_t` is Bitcoin Core's bread and butter, and we figured we could minimize compatibility issues with reusing bitcoin code if we stuck with it.  Before that decision was made however `uint64_t` was all over the place, and I think I'm guilty of using them since then probably too :(

> ... fixes it and the tests run fine then.. 

You are a star mate, I think I'll expand on that just a little too because the auditor should be complaining itself if it's asked to increase it's token count cache by a negative amount.

Thanks again mate :)

**Comment by dexX7** [comment]
> Well, originally we weren't actually going to cap token counts at 9 gazillion ...

Gotcha, this is what I assumed. :) I see some more in the context of crowdfund participation, and `CMPTransaction` even uses an `uint64_t`.

Over time, but very carefully (!) they should be replaced by proper types. This should, by the way, also be expanded to other data types, and correct, fixed length integers should be used whenever possible (e.g. `uint32_t` instead of `unsigned int`, which is wider on x64 systems, for property identifiers).

Right now, everything works as expected, but your case is a good example, where this can result in unexpected behavior, so this is rather an improvement for the future, to increase robustness, instead of a bug fix.
